# Generated by Django 5.1.4 on 2024-12-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
    ]
