# Generated by Django 5.1.4 on 2024-12-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Оплата банковской картой'), ('cash', 'Оплата наличными при получении товара')], default='card', max_length=10),
        ),
    ]
