# Generated by Django 5.1.4 on 2025-01-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
