# Generated by Django 5.1.4 on 2025-01-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
